---
title: "TD(31 mars)"
author: "Chang-Beom LEE"
date: "3/31/2022"
output: html_document
  html_document: 
    number_sections: yes
    toc: yes
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(cache = TRUE)
knitr::opts_chunk$set(eval = TRUE)
knitr::opts_chunk$set(warning = FALSE)
```

```{r}
library(sf)
library(mapsf)
data <- st_read("vote.gpkg", "jointure")
apply(data [,14:18, drop = T], 2,sum)
summary(data[,14:15, drop = T])
data <- data [,14:15]
names (data) [1:2] <- c("HERVE")
palette <- terrain.colors(8, rev = T)
seuils <- c(0,25, 50, 75, 100, 125, 150, 175, 200)
png("resultHERVE.png", width = 4000, height = 4000, res = 400)
mf_choro(data,  var = "HERVE", breaks = seuils, pal = palette, border = NA, leg_pos = "n")
mf_label(data, "HERVE")
mf_inset_on(data, pos = "topright")
par(mar = c(2,2,2,2))
hist(data$HERVE, border = NA, breaks = seuils, right = F, col=palette, main = "", xlab = "", ylab="")
mf_inset_off()
dev.off()
```